name: Run Docker on Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/docker-deploy

jobs:
  build-and-run:
    runs-on: it3k-2025
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        run: docker run -d --name my-container -p 80:3000 my-app

      - name: Check running containers
        run: docker ps
